### ISSUE TITLE
rethink how nodes are initialized vs started

### ISSUE THREAD

**Issue by MonsieurNicolas** [stellar/stellar_core_commander#103]
Right now initializing nodes is done during the same step than starting them. This leads to problems when trying to bring up complex topologies where we need to start nodes roughly at the same time (ie, within seconds of each other) to avoid triggering catchup.

Specifically, `local_process:setup` performs a few expensive operations, such as database initialization and history archive initialization.

That code is called by `process:run`:
```ruby
    def run
      raise Process::AlreadyRunning, "already running!" if running?
      raise Process::Crash, "process #{name} has crashed. cannot run process again" if crashed?

      setup ##### <<< This is the expensive call
      launch_process
      @launched = true

      wait_for_http 
      set_upgrades
    end
```

The solution is probably to decouple those two steps by:
* adding a new boolean field "initialized" (making `setup` noop if it was already run)
* changing `commander:start_all_processes` to first loop and initialize nodes before calling `p.run`
* there might be a need for forcing `setup` to do its work (or a way to clear the `initialized` bool), looking at how `process` is used, it doesn't seem to be the case though

**Comment by nullstyle** [comment]
> there might be a need for forcing `setup` to do its work

We'll add a new method named `setup!`

> adding a new boolean field "initialized" (making setup noop if it was already run)

Let's call it `@is_setup` to tie it to the `setup` method and to avoid attachment with the ruby keyword `initialize`(a constructor)

---

Other than that, I'm fine with this approach.  It shouldn't compromise horizon's use of `scc`
