### ISSUE TITLE
mktmpdir NoMethodError if no destination provided in bin/scc

### ISSUE THREAD

**Issue by marta-lokhova** [stellar/stellar_core_commander#99]
Encountered the following issue while running scc locally. If I do not supply --destination, scc fails with the following error:
```
/Library/Ruby/Gems/2.3.0/gems/stellar_core_commander-0.0.12/bin/scc:110:in `make_commander': undefined method `mktmpdir' for Dir:Class (NoMethodError)
Did you mean?  mkdir
	from /Library/Ruby/Gems/2.3.0/gems/stellar_core_commander-0.0.12/bin/scc:71:in `run'
	from /Library/Ruby/Gems/2.3.0/gems/stellar_core_commander-0.0.12/bin/scc:135:in `<top (required)>'
	from /usr/local/bin/scc:22:in `load'
	from /usr/local/bin/scc:22:in `<main>'
``` 
I think adding "require `tmpdir`" to bin/scc should remedy this (tried in irb).

**Comment by marta-lokhova** [comment]
Fixed in the latest merge.

**Comment by fuzzyami** [comment]
@MonsieurNicolas hello again. not sure who's maintaining this gem, but please consider publishing an updated gem that fixes this issue. Its _very easy_ to hit this issue, especially if you know nothing about ruby.
